### ISSUE TITLE
Installation to emmc?

### ISSUE THREAD

**Issue by TenoWano** [hexdump0815/linux-mainline-on-arm-chromebooks#2]
First, this project has been the best Linux experience on my Chromebook and in an ARM device in general. I'm am running off of a SD card, but I am experiencing major 8-10 second slowdowns when loading things (probably from the slow speed of the SD). I have no use for Chrome OS, so I want to copy my installation to the emmc if possible. Doing a fresh install onto emmc would also be fine, but not preferred. I have very little command line experience, enough to use cd and apt comfortably. Having step by step instructions would be nice. This project is amazing and using it on emmc could make it even better.

I'm using the Samsung Chromebook 2 peach-pi system with a 16gb SD card (when formated around 14.8GB)

**Comment by TenoWano** [comment]
I was able to do it after some reasearch. For anyone interested, I booted the SD card first, then used dd to flash the image to the emmc after it was extracted.

**Comment by hexdump0815** [comment]
hi @TenoWano , i'm happy to hear that it is working well for you. is everything working well on the peach pi (u-boot, sound, wifi, bt, camera, etc.)? i have no access to one, so i could not test it directly on this device. could you maybe paste the output of "cat /proc/asound/cards" from your peach pi here?

a lot of thanks in advance and best wishes - hexdump

**Comment by TenoWano** [comment]
I am sorry, but I made typo, it is a peach-pit system. The only problems are those you had listed and it states that I only have 3 GB available, so I don't think the image is expanding itself. I tried using Gparted, but expanding the main btrfs partition causes it to fail to boot.
