### ISSUE TITLE
Have you considered a kexec-based bootstrap?

### ISSUE THREAD

**Issue by sraustein** [hexdump0815/linux-mainline-on-arm-chromebooks#33]
Hi.  Nice package, was impressed at how quickly it let me boot Debian on an Acer Spin.  Always wanted to run Inkscape on a touch screen, now I can.

Given the discussion of how the ChromeOS kernel partition works on these ARM64 machines, I was wondering whether you'd investigated using a `kexec`-based bootloader like https://github.com/BayLibre/k-boot ?  Seems like it might be a good fit, for two reasons:

1. It would allow treating the kernel partition as a bootloader while keeping the "real" kernel in the regular filesystem, which would make it much easier to track upstream kernel changes using normal APT upgrades.
2. It would allow things like enabling LUKS2 in that bootloader, so that one could choose to encrypt `/boot`.

Not an urgent problem by any means.  Might try it myself when I have time (so, any year now...).

**Comment by hexdump0815** [comment]
currently i'm not thinking about it - maybe at some later point - see also: https://github.com/hexdump0815/imagebuilder/discussions/242

**Comment by sraustein** [comment]
Fair enough, and thanks for the pointers.  Will let you know if I get anywhere interesting with this.
